# Generated by Django 5.0.3 on 2024-04-15 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hall', '0002_seattype_seatdetail'),
        ('movie', '0002_alter_movie_trailer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Normal', 'Normal'), ('Couple', 'Couple'), ('VIP', 'VIP')], max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('remaining_seats', models.IntegerField()),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall.hall')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screening.screeningprice')),
            ],
        ),
    ]
