# Generated by Django 5.0.3 on 2024-04-15 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hall', '0002_seattype_seatdetail'),
        ('screening', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screening.screening')),
                ('seat_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall.seatdetail')),
            ],
        ),
    ]
