# Generated by Django 5.0.3 on 2024-04-25 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('hall', '0003_rename_seats_column_seatdetail_seat_column'),
        ('screening', '0002_remove_screeningprice_type_screeningprice_day_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('seat_detail', 'screening')},
        ),
    ]
