# Generated by Django 5.0.3 on 2024-03-25 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_limit', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DirectorAndActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='avatars/')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], max_length=3)),
                ('birth_date', models.DateField()),
                ('role', models.CharField(choices=[('Đạo diễn', 'Đạo diễn'), ('Diễn viên', 'Diễn viên'), ('Đạo diễn và diễn viên', 'Đạo diễn và diễn viên')], max_length=30)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('poster', models.ImageField(upload_to='uploads/%Y/%m')),
                ('trailer', models.URLField(null=True)),
                ('release_date', models.DateField()),
                ('content', models.TextField()),
                ('duration', models.IntegerField()),
                ('age_limit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.agelimit')),
                ('director_and_actor', models.ManyToManyField(to='movie.directorandactor')),
                ('genre', models.ManyToManyField(to='movie.genre')),
                ('language', models.ManyToManyField(to='movie.language')),
            ],
        ),
    ]
