# Generated by Django 5.0.3 on 2024-04-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='tags',
            field=models.ManyToManyField(to='review.reviewtag'),
        ),
        migrations.DeleteModel(
            name='ReviewTagDetail',
        ),
    ]
