# Generated by Django 5.0.3 on 2024-03-29 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
