# Generated by Django 5.0.3 on 2024-04-01 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0003_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
