# Generated by Django 5.0.3 on 2024-04-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0005_customuser_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
