# Generated by Django 5.0.3 on 2024-04-22 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0006_customuser_address_id'),
        ('hall', '0003_rename_seats_column_seatdetail_seat_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavoriteCinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall.cinema')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'cinema')},
            },
        ),
    ]
