# Generated by Django 5.0.3 on 2024-04-25 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0007_userfavoritecinema'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
