# Generated by Django 5.0.3 on 2024-04-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0008_customuser_stripe_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stripe_pm_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
