# Generated by Django 5.0.3 on 2024-04-17 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0002_seattype_seatdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seatdetail',
            old_name='seats_column',
            new_name='seat_column',
        ),
    ]
